version: '3.8'

services:
  kokoro-tts:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:v0.2.2
    container_name: kokoro-tts
    ports:
      - "8880:8880"
    environment:
      - PORT=8880
    restart: unless-stopped
